services:
  - type: web
    name: michelangelo
    env: node
    plan: free # o el plan que prefieras
    rootDir: .
    buildCommand: |
      npm install --prefix backend && npm run build --prefix backend &&
      cd frontend &&
      npm install &&
      npm run build &&
      cd .. &&
      mkdir -p backend/dist/public &&
      mv frontend/dist/* backend/dist/public/
    startCommand: "npm start --prefix backend"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
